### ISSUE TITLE
File extension issues extremely not fixed

### ISSUE THREAD

**Issue by ImportTaste** [herp-a-derp/xA-Scraper#44]
```
Main.FaGet.StatusMgr - ERROR - Traceback (most recent call last):
  File "U:\xA-Scraper\xascraper\modules\scraper_base.py", line 540, in getArtist
    ret = self._fetch_retrier(dlPathBase, pageURL, artist)
  File "U:\xA-Scraper\xascraper\modules\scraper_base.py", line 501, in _fetch_retrier
    ret = self._getArtPage(*args, **kwargs)
  File "U:\xA-Scraper\xascraper\modules\fa\faScrape.py", line 239, in _getArtPage
    filePath = self.save_file(filePath, imgdat)
  File "U:\xA-Scraper\xascraper\modules\scraper_base.py", line 210, in save_file
    fqfilename = insertExtIfNeeded(fqfilename, file_content)
  File "U:\xA-Scraper\xascraper\modules\scraper_base.py", line 58, in insertExtIfNeeded
    root, ext = os.path.splitext(fqfilename)
NameError: name 'fqfilename' is not defined
```

**Comment by ImportTaste** [comment]
This might be related to the site jpg-compressing pngs that are above 1280 in either their x or y dimensions, and then not changing the extension.

**Comment by fake-name** [comment]
No, this is just really dumb copy+paste stupid.
