### ISSUE TITLE
Uncaught exception uncaught and redundant extension placement

### ISSUE THREAD

**Issue by ImportTaste** [herp-a-derp/xA-Scraper#46]
I modified the filename, author, and id of this URL, but the redundant placement of 'swf' is just how it was originally: http://d.facdn.netswf/art/herpaderp/1234567890/1234567890.swfherpaderp_imodifiedthisurl_video.swf

```
Main - CRITICAL - Uncaught exception!
Main - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "U:\xA-Scraper\xascraper\modules\scraper_base.py", line 540, in getArtist
    ret = self._fetch_retrier(dlPathBase, pageURL, artist)
  File "U:\xA-Scraper\xascraper\modules\scraper_base.py", line 501, in _fetch_retrier
    ret = self._getArtPage(*args, **kwargs)
  File "U:\xA-Scraper\xascraper\modules\fa\faScrape.py", line 226, in _getArtPage
    imgdat = self.wg.getpage(imgurl)                                                    # Request Image
  File "C:\Python37\lib\site-packages\WebRequest\WebRequestClass.py", line 186, in getpage
    return self._unwaf_func("_getpage", requestedUrl, *args, **kwargs)
  File "C:\Python37\lib\site-packages\WebRequest\WebRequestClass.py", line 151, in _unwaf_func
    return target_func(requestedUrl, *args, **kwargs)
  File "C:\Python37\lib\site-packages\WebRequest\WebRequestClass.py", line 636, in _getpage
    err_content=err_content, err_code=err_code, err_reason=err_reason)
WebRequest.Exceptions.FetchFailureError: <FetchFailureError -1 -> 'Unhandled general exception' for url: http://d.facdn.netswf/art/herpaderp/1234567890/1234567890.swfherpaderp_imodifiedthisurl_video.swf ({Traceback (most recent call last):
  File "C:\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Python37\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python37\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python37\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python37\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Python37\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\Python37\lib\http\client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Python37\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python37\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\WebRequest\WebRequestClass.py", line 538, in _getpage
    pghandle = self.opener.open(pgreq, timeout=self.timeout)                                    # Get Webpage
  File "C:\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Python37\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python37\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
})>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "U:\xA-Scraper\manage\__main__.py", line 101, in <module>
    go()
  File "U:\xA-Scraper\manage\__main__.py", line 95, in go
    two_arg_go(sys.argv[1], sys.argv[2])
  File "U:\xA-Scraper\manage\__main__.py", line 48, in two_arg_go
    do_fetch([param])
  File "U:\xA-Scraper\manage\scrape_manage.py", line 75, in do_fetch
    do_plugin(plgname)
  File "U:\xA-Scraper\manage\scrape_manage.py", line 51, in do_plugin
    plg.runScraper(namespace)
  File "U:\xA-Scraper\xascraper\modules\scraper_base.py", line 679, in runScraper
    instance.go(ctrlNamespace=managedNamespace)
  File "U:\xA-Scraper\xascraper\modules\scraper_base.py", line 663, in go
    errored  |= future.result()
  File "C:\Python37\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "U:\xA-Scraper\xascraper\modules\scraper_base.py", line 609, in getArtist
    except Exceptions.UnrecoverableFailureException:
NameError: name 'Exceptions' is not defined
```

**Comment by ImportTaste** [comment]
I left a couple important comments on this commit: https://github.com/herp-a-derp/xA-Scraper/commit/62a73a9992b407f523a4009427e5a5738489211c

**Comment by herp-a-derp** [comment]
Out of curiosity, if you try to browse to the relevant URL, does it work?

If the page works properly, but fetching it fails, I'd need to see the actual page to figure out what's going on. 

You can e-mail me about it if you don't want to post URLs publicly. anything \<at\> fake-url \<dot\> com will get to me.

**Comment by ImportTaste** [comment]
Look at the URL. See how many times 'swf' occurs. It's placing them redundantly.
